function daysAgo(n, hour = 12, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d;
}

let id = 1;

const SAMPLE_EXPENSES = [
  {
    id: id++,
    title: "Grocery shopping",
    description: "Weekly market run",
    category: "Shopping",
    amount: 124,
    createdAt: daysAgo(0, 0, 45),
  },
  {
    id: id++,
    title: "Electricity bill",
    description: "Monthly electricity",
    category: "Bills",
    amount: 185,
    createdAt: daysAgo(0, 5, 20),
  },
  {
    id: id++,
    title: "Bus fare",
    description: "Public bus commute",
    category: "Transport",
    amount: 30,
    createdAt: daysAgo(0, 7, 10),
  },
  {
    id: id++,
    title: "Lunch with friends",
    description: "Sushi restaurant",
    category: "Food",
    amount: 42,
    createdAt: daysAgo(0, 12, 35),
  },
  {
    id: id++,
    title: "Streaming subscription",
    description: "Monthly Netflix",
    category: "Entertainment",
    amount: 16,
    createdAt: daysAgo(0, 9, 50),
  },
  {
    id: id++,
    title: "Pharmacy",
    description: "Vitamins and supplements",
    category: "Health",
    amount: 28,
    createdAt: daysAgo(0, 15, 5),
  },
  {
    id: id++,
    title: "Parking fee",
    description: "Downtown parking garage",
    category: "Other",
    amount: 12,
    createdAt: daysAgo(0, 11, 20),
  },
  {
    id: id++,
    title: "Steak dinner",
    description: "Dinner at steakhouse",
    category: "Food",
    amount: 1560,
    createdAt: daysAgo(1, 20, 30),
  },
  {
    id: id++,
    title: "Movie tickets",
    description: "Weekend movie night",
    category: "Entertainment",
    amount: 35,
    createdAt: daysAgo(1, 15, 45),
  },
  {
    id: id++,
    title: "Doctor visit",
    description: "Routine checkup",
    category: "Health",
    amount: 2500,
    createdAt: daysAgo(3, 16, 30),
  },
  {
    id: id++,
    title: "Weekly groceries",
    description: "Supermarket haul",
    category: "Shopping",
    amount: 41,
    createdAt: daysAgo(3, 11, 15),
  },
  {
    id: id++,
    title: "Internet bill",
    description: "Monthly internet",
    category: "Bills",
    amount: 100,
    createdAt: daysAgo(5, 17, 40),
  },
  {
    id: id++,
    title: "Taxi ride",
    description: "Ride to airport",
    category: "Transport",
    amount: 8,
    createdAt: daysAgo(5, 6, 25),
  },
  {
    id: id++,
    title: "Coffee & snacks",
    description: "Afternoon cafe visit",
    category: "Food",
    amount: 6,
    createdAt: daysAgo(7, 16, 50),
  },
  {
    id: id++,
    title: "New shoes",
    description: "New running shoes",
    category: "Shopping",
    amount: 599,
    createdAt: daysAgo(7, 12, 10),
  },
  {
    id: id++,
    title: "Concert tickets",
    description: "Live music show",
    category: "Entertainment",
    amount: 450,
    createdAt: daysAgo(10, 19, 55),
  },
  {
    id: id++,
    title: "Coffee",
    description: "Morning brew",
    category: "Food",
    amount: 5,
    createdAt: daysAgo(28, 8, 15),
  },
  {
    id: id++,
    title: "Gas station",
    description: "Fuel",
    category: "Transport",
    amount: 45,
    createdAt: daysAgo(28, 17, 30),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Sandwich shop",
    category: "Food",
    amount: 12,
    createdAt: daysAgo(27, 12, 20),
  },
  {
    id: id++,
    title: "Uber",
    description: "Ride home",
    category: "Transport",
    amount: 18,
    createdAt: daysAgo(27, 21, 10),
  },
  {
    id: id++,
    title: "Groceries",
    description: "Milk and bread",
    category: "Shopping",
    amount: 22,
    createdAt: daysAgo(26, 9, 45),
  },
  {
    id: id++,
    title: "Spotify",
    description: "Monthly subscription",
    category: "Entertainment",
    amount: 11,
    createdAt: daysAgo(26, 10, 0),
  },
  {
    id: id++,
    title: "Pharmacy",
    description: "Cold medicine",
    category: "Health",
    amount: 15,
    createdAt: daysAgo(25, 14, 30),
  },
  {
    id: id++,
    title: "Dinner out",
    description: "Pizza place",
    category: "Food",
    amount: 28,
    createdAt: daysAgo(25, 19, 15),
  },
  {
    id: id++,
    title: "Bus pass",
    description: "Weekly pass",
    category: "Transport",
    amount: 35,
    createdAt: daysAgo(24, 7, 0),
  },
  {
    id: id++,
    title: "Snacks",
    description: "Convenience store",
    category: "Food",
    amount: 8,
    createdAt: daysAgo(24, 16, 45),
  },
  {
    id: id++,
    title: "Electric bill",
    description: "Monthly payment",
    category: "Bills",
    amount: 92,
    createdAt: daysAgo(23, 8, 0),
  },
  {
    id: id++,
    title: "Movie rental",
    description: "Streaming rental",
    category: "Entertainment",
    amount: 6,
    createdAt: daysAgo(23, 20, 30),
  },
  {
    id: id++,
    title: "Breakfast",
    description: "Cafe",
    category: "Food",
    amount: 14,
    createdAt: daysAgo(22, 9, 20),
  },
  {
    id: id++,
    title: "Gym membership",
    description: "Monthly",
    category: "Health",
    amount: 40,
    createdAt: daysAgo(22, 11, 0),
  },
  {
    id: id++,
    title: "Office supplies",
    description: "Notebooks",
    category: "Other",
    amount: 19,
    createdAt: daysAgo(21, 10, 15),
  },
  {
    id: id++,
    title: "Lunch delivery",
    description: "Food delivery app",
    category: "Food",
    amount: 24,
    createdAt: daysAgo(21, 13, 0),
  },
  {
    id: id++,
    title: "Parking",
    description: "Street parking",
    category: "Transport",
    amount: 10,
    createdAt: daysAgo(20, 8, 30),
  },
  {
    id: id++,
    title: "Coffee",
    description: "Afternoon pick-me-up",
    category: "Food",
    amount: 6,
    createdAt: daysAgo(20, 15, 20),
  },
  {
    id: id++,
    title: "Amazon order",
    description: "Household items",
    category: "Shopping",
    amount: 67,
    createdAt: daysAgo(19, 18, 45),
  },
  {
    id: id++,
    title: "Netflix",
    description: "Monthly",
    category: "Entertainment",
    amount: 16,
    createdAt: daysAgo(19, 9, 0),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Salad bar",
    category: "Food",
    amount: 13,
    createdAt: daysAgo(18, 12, 30),
  },
  {
    id: id++,
    title: "Dry cleaning",
    description: "Shirts",
    category: "Other",
    amount: 32,
    createdAt: daysAgo(18, 17, 0),
  },
  {
    id: id++,
    title: "Groceries",
    description: "Weekly haul",
    category: "Shopping",
    amount: 78,
    createdAt: daysAgo(17, 10, 0),
  },
  {
    id: id++,
    title: "Beer",
    description: "Six-pack",
    category: "Food",
    amount: 12,
    createdAt: daysAgo(17, 19, 30),
  },
  {
    id: id++,
    title: "Train ticket",
    description: "Commute",
    category: "Transport",
    amount: 22,
    createdAt: daysAgo(16, 7, 15),
  },
  {
    id: id++,
    title: "Dinner",
    description: "Thai restaurant",
    category: "Food",
    amount: 38,
    createdAt: daysAgo(16, 20, 0),
  },
  {
    id: id++,
    title: "Phone bill",
    description: "Monthly",
    category: "Bills",
    amount: 65,
    createdAt: daysAgo(15, 8, 0),
  },
  {
    id: id++,
    title: "Valentine's flowers",
    description: "Bouquet",
    category: "Other",
    amount: 45,
    createdAt: daysAgo(15, 18, 0),
  },
  {
    id: id++,
    title: "Brunch",
    description: "Weekend brunch",
    category: "Food",
    amount: 35,
    createdAt: daysAgo(14, 11, 30),
  },
  {
    id: id++,
    title: "Bookstore",
    description: "New book",
    category: "Entertainment",
    amount: 18,
    createdAt: daysAgo(14, 15, 0),
  },
  {
    id: id++,
    title: "Coffee",
    description: "Morning",
    category: "Food",
    amount: 5,
    createdAt: daysAgo(13, 8, 45),
  },
  {
    id: id++,
    title: "Lyft",
    description: "Airport ride",
    category: "Transport",
    amount: 42,
    createdAt: daysAgo(13, 5, 30),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Burger joint",
    category: "Food",
    amount: 16,
    createdAt: daysAgo(12, 12, 0),
  },
  {
    id: id++,
    title: "Vitamins",
    description: "Supplements",
    category: "Health",
    amount: 28,
    createdAt: daysAgo(12, 14, 0),
  },
  {
    id: id++,
    title: "Water bill",
    description: "Monthly",
    category: "Bills",
    amount: 38,
    createdAt: daysAgo(11, 9, 0),
  },
  {
    id: id++,
    title: "Snacks",
    description: "Vending machine",
    category: "Food",
    amount: 4,
    createdAt: daysAgo(11, 16, 20),
  },
  {
    id: id++,
    title: "Target run",
    description: "Cleaning supplies",
    category: "Shopping",
    amount: 54,
    createdAt: daysAgo(10, 17, 30),
  },
  {
    id: id++,
    title: "Pizza",
    description: "Takeout",
    category: "Food",
    amount: 26,
    createdAt: daysAgo(10, 19, 0),
  },
  {
    id: id++,
    title: "Bus fare",
    description: "Daily commute",
    category: "Transport",
    amount: 6,
    createdAt: daysAgo(9, 7, 45),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Soup and salad",
    category: "Food",
    amount: 11,
    createdAt: daysAgo(9, 12, 30),
  },
  {
    id: id++,
    title: "Concert",
    description: "Local band",
    category: "Entertainment",
    amount: 25,
    createdAt: daysAgo(8, 20, 0),
  },
  {
    id: id++,
    title: "Drinks",
    description: "Bar",
    category: "Food",
    amount: 22,
    createdAt: daysAgo(8, 22, 30),
  },
  {
    id: id++,
    title: "Groceries",
    description: "Produce",
    category: "Shopping",
    amount: 34,
    createdAt: daysAgo(7, 10, 0),
  },
  {
    id: id++,
    title: "Car wash",
    description: "Full service",
    category: "Transport",
    amount: 15,
    createdAt: daysAgo(7, 14, 0),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Mexican",
    category: "Food",
    amount: 18,
    createdAt: daysAgo(6, 13, 0),
  },
  {
    id: id++,
    title: "Haircut",
    description: "Barber",
    category: "Other",
    amount: 30,
    createdAt: daysAgo(6, 16, 0),
  },
  {
    id: id++,
    title: "Internet",
    description: "Monthly bill",
    category: "Bills",
    amount: 55,
    createdAt: daysAgo(5, 8, 0),
  },
  {
    id: id++,
    title: "Coffee",
    description: "Espresso",
    category: "Food",
    amount: 5,
    createdAt: daysAgo(5, 9, 30),
  },
  {
    id: id++,
    title: "Lunch",
    description: "Sushi",
    category: "Food",
    amount: 32,
    createdAt: daysAgo(4, 12, 15),
  },
  {
    id: id++,
    title: "Uber",
    description: "Evening ride",
    category: "Transport",
    amount: 14,
    createdAt: daysAgo(4, 21, 0),
  },
  {
    id: id++,
    title: "Groceries",
    description: "Weekly run",
    category: "Shopping",
    amount: 89,
    createdAt: daysAgo(3, 11, 0),
  },
  {
    id: id++,
    title: "Movie",
    description: "Theater tickets",
    category: "Entertainment",
    amount: 28,
    createdAt: daysAgo(3, 19, 30),
  },
  {
    id: id++,
    title: "Breakfast",
    description: "Bagels",
    category: "Food",
    amount: 9,
    createdAt: daysAgo(2, 8, 30),
  },
  {
    id: id++,
    title: "Gas",
    description: "Fill up",
    category: "Transport",
    amount: 52,
    createdAt: daysAgo(2, 17, 0),
  },
  {
    id: id++,
    title: "Dinner",
    description: "Italian",
    category: "Food",
    amount: 48,
    createdAt: daysAgo(1, 19, 30),
  },
  {
    id: id++,
    title: "Pharmacy",
    description: "Prescription",
    category: "Health",
    amount: 22,
    createdAt: daysAgo(1, 15, 0),
  },
];

export default SAMPLE_EXPENSES;
